name: CI/CD Inventory API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_CONTAINER_REGISTRY: "acrinventorylisa" 
  CONTAINER_APP_NAME: "ca-inventory-api-dev"
  RESOURCE_GROUP: "rg-LisaE-dev"
  CONTAINER_APP_ENV: "cae-inventory-dev-lisa"
  
jobs:
  # part 1, testing
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: CloudNativeInventory.sln
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build project
        run: dotnet build --no-restore --configuration Release
        
      - name: Run automated tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  # part 2, build and push (to Germany)
  build-and-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/inventory-api:${{ github.sha }} \
                       -t ${{ secrets.ACR_LOGIN_SERVER }}/inventory-api:latest \
                       -f CloudNativeInventory.Api/Dockerfile .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/inventory-api:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/inventory-api:latest

  # Part 3, deploy (to Poland)
  deploy:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/inventory-api:${{ github.sha }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENV }}
